In [1]:
import pandas as pd
import numpy as np

In [2]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 002B-031C

 Directory of C:\Users\user\4ik25cs069

09/07/2026  09:45 AM    <DIR>          .
09/07/2026  09:42 AM    <DIR>          ..
09/07/2026  09:43 AM    <DIR>          .ipynb_checkpoints
09/07/2026  09:45 AM               835 Untitled.ipynb
               1 File(s)            835 bytes
               3 Dir(s)  172,794,912,768 bytes free

In [9]:
df=pd.read_csv("student_performance.csv")

In [10]:
print(df)

        student_id  weekly_self_study_hours  attendance_percentage  \
0                1                     18.5                   95.6
1                2                     14.0                   80.0
2                3                     19.5                   86.3
3                4                     25.7                   70.2
4                5                     13.4                   81.9
...            ...                      ...                    ...
999995      999996                     18.0                   95.5
999996      999997                     15.7                   82.7
999997      999998                     14.2                   85.1
999998      999999                     25.3                   90.0
999999     1000000                     18.3                   84.6

        class_participation  total_score grade
0                       3.8         97.9     A
1                       2.5         83.9     B
2                       5.3        100.0     A
3                       7.0        100.0     A
4                       6.9         92.0     A
...                     ...          ...   ...
999995                  4.8        100.0     A
999996                  6.7         88.3     A
999997                  5.8         87.9     A
999998                  5.3        100.0     A
999999                  4.1        100.0     A

[1000000 rows x 6 columns]

In [11]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [12]:
df.tail()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [13]:
df.shape

(1000000, 6)

In [14]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='str')

In [16]:
df.dtypes

student_id                   int64
weekly_self_study_hours    float64
attendance_percentage      float64
class_participation        float64
total_score                float64
grade                          str
dtype: object

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  str
dtypes: float64(4), int64(1), str(1)
memory usage: 45.8 MB

In [25]:
df.describe()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,15.029127,84.711046,5.985203,84.283845
std,288675.278932,6.899431,9.424143,1.956421,15.432969
min,1.000000,0.000000,50.000000,0.000000,9.400000
25%,250000.750000,10.300000,78.300000,4.700000,73.900000
50%,500000.500000,15.000000,85.000000,6.000000,87.500000
75%,750000.250000,19.700000,91.800000,7.300000,100.000000
max,1000000.000000,40.000000,100.000000,10.000000,100.000000

In [26]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [27]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.iloc[0:5]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [34]:
df["attendance_percentage"].mean()

np.float64(84.711046)

In [35]:
df.drop_duplicates()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [36]:
df.isnull()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
999995,False,False,False,False,False,False
999996,False,False,False,False,False,False
999997,False,False,False,False,False,False
999998,False,False,False,False,False,False
999999,False,False,False,False,False,False

In [37]:
df["weekly_self_study_hours"].mean()

np.float64(15.0291269)

In [38]:
df["weekly_self_study_hours"].median()

np.float64(15.0)

In [39]:
df["weekly_self_study_hours"].mode()

0    0.0
Name: weekly_self_study_hours, dtype: float64

In [40]:
df["weekly_self_study_hours"].var()

np.float64(47.6021484158448)

In [41]:
df["weekly_self_study_hours"].std()

np.float64(6.8994310211672385)

In [42]:
df["weekly_self_study_hours"].min()

np.float64(0.0)

In [43]:
df["weekly_self_study_hours"].max()

np.float64(40.0)

In [44]:
df["weekly_self_study_hours"].count()

np.int64(1000000)

In [45]:
df["weekly_self_study_hours"].unique()

array([18.5, 14. , 19.5, 25.7, 13.4, 26.1, 20.4, 11.7, 18.8, 11.8, 16.7,
        1.6,  2.9, 11.1,  7.9, 17.2,  8.6,  5.1, 25.3, 15.5,  5. , 11.2,
       15.8,  6.9, 17.6, 10.8, 13. , 28. , 14.9,  7.6, 20.8,  6.5, 16.5,
        1.3,  5.7, 16.4, 20.2, 16.2, 14.2, 12.9,  4.7, 10. , 22.4, 17.4,
        2.7, 17.3, 12.3, 10.3, 19.3, 22.2, 21.5,  9.1, 12.8, 21.8, 11.6,
       13.7,  7.3,  6.6, 20.7, 24.5, 14.5, 22. , 17.5, 10.5, 25.8, 14.7,
       26. ,  0. , 15.6,  1.1, 13.5, 11.4,  9.3, 11.5, 21.4, 11.3, 18.6,
       15.7, 10.1, 12.7,  4.8, 17.1, 16.8, 15. , 12.1, 12.6,  9.4, 13.9,
       17.8, 28.2, 14.8, 15.4, 32.2,  6.8, 23. , 20.3, 20.5, 24.8,  5.2,
       19.1, 30.3,  8.1, 11. ,  4.1, 18.3,  9.5,  6.4, 16.6, 24.1,  3.7,
       16.3,  6.3,  5.8, 18.7, 10.2, 28.1,  6.7, 19.6,  8.2, 23.1, 21.7,
       17.9, 28.3, 13.3,  9.7,  8.8, 16.9, 15.1, 25.2, 13.1, 34. , 19.4,
        9. ,  7.5, 18.4, 20. ,  4.4, 11.9, 21. , 17.7, 16.1,  7. , 18.9,
       22.6,  5.4,  8.4, 40. , 19. , 22.9,  9.6, 31.2,  1.9, 19.8,  9.9,
       15.3, 10.4, 30. ,  0.8, 21.1, 27.4,  6.2, 29.9, 23.9, 18.1,  8.5,
       14.6,  7.8, 13.2, 26.4, 15.9, 25.1,  4.9, 18.2, 17. , 10.6, 10.9,
       20.9, 21.3,  9.2, 13.6, 22.7, 14.1, 19.2, 29.6,  8. ,  8.7, 12.2,
       15.2, 30.1,  0.1, 27.8, 23.3,  3. , 23.7,  3.8,  7.1,  4.3,  9.8,
       25.9, 29.4, 27.3, 24.6,  0.7, 25.5,  5.3,  3.1,  0.5, 14.4,  5.9,
       19.7, 14.3, 28.8, 26.5, 36.6, 22.8,  8.3,  7.4, 26.8, 21.2, 25.4,
        7.7,  8.9, 28.4,  3.3,  2.4,  3.6,  3.4, 23.2, 12. , 29.5, 23.4,
       12.5, 26.7,  4.6, 30.9, 22.3,  2.5, 32.1, 20.1, 24.4, 26.2,  3.2,
        6. ,  4.5, 19.9, 27.9, 33. , 12.4,  7.2,  0.4, 26.9,  5.6, 21.9,
       22.1,  2.1, 10.7,  5.5, 33.4, 32.9, 27.7,  4. , 18. ,  6.1, 21.6,
       23.8, 22.5, 24.9, 31.1, 27.6, 29.1, 13.8, 32.7, 24.7, 16. , 24.3,
        1.8,  3.9, 24.2, 27.2, 27.1,  2.8,  1. , 31.8, 26.3, 30.8, 31. ,
        3.5, 30.5, 33.1, 23.6, 23.5, 32.5,  1.2, 27. , 30.2, 33.2, 24. ,
       29. , 25.6,  2.6, 26.6, 20.6, 37.4, 28.6,  2.2, 30.6, 28.7, 33.5,
       37. ,  1.7, 34.3, 25. , 31.9, 29.2, 29.7, 36.8, 31.5, 28.9, 35.6,
       35.9, 32. , 33.3,  0.3,  4.2, 33.9,  1.5,  0.2,  2.3, 27.5, 35.1,
        2. , 29.3, 28.5, 32.6, 32.4, 37.7,  0.9, 37.1, 34.7, 31.4, 30.4,
        0.6,  1.4, 31.7, 32.8, 36.5, 31.3, 35.4, 35.5, 34.8, 36.7, 34.5,
       31.6, 39.7, 33.7, 29.8, 34.1, 38.6, 30.7, 34.4, 34.6, 38. , 35.8,
       34.9, 33.8, 36.3, 39. , 37.3, 32.3, 34.2, 35.2, 36. , 33.6, 37.5,
       35.7, 36.9, 35.3, 36.1, 38.5, 35. , 38.4, 37.9, 38.3, 38.1, 39.8,
       37.6, 38.7, 38.8, 37.2, 39.3, 39.2, 36.4, 39.1, 39.5, 36.2, 39.4,
       39.6, 38.2, 39.9, 37.8, 38.9])

In [46]:
df["weekly_self_study_hours"].nunique()

401

In [47]:
df.iloc[400:402]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
400,401,3.8,85.8,4.7,67.2,C
401,402,10.8,88.7,4.5,67.8,C

In [49]:
df["weekly_self_study_hours"].value_counts()

weekly_self_study_hours
0.0     16492
16.0     5829
14.9     5774
15.1     5751
15.2     5735
        ...
39.3       10
39.1       10
39.9       10
39.7        9
39.4        9
Name: count, Length: 401, dtype: int64

In [50]:
df.isnull()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
999995,False,False,False,False,False,False
999996,False,False,False,False,False,False
999997,False,False,False,False,False,False
999998,False,False,False,False,False,False
999999,False,False,False,False,False,False

In [51]:
df.isnull().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [52]:
df.isnull().mean()*100

student_id                 0.0
weekly_self_study_hours    0.0
attendance_percentage      0.0
class_participation        0.0
total_score                0.0
grade                      0.0
dtype: float64

In [54]:
df.dropna()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [55]:
df.fillna(0)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [56]:
df["weekly_self_study_hours"]

0         18.5
1         14.0
2         19.5
3         25.7
4         13.4
          ...
999995    18.0
999996    15.7
999997    14.2
999998    25.3
999999    18.3
Name: weekly_self_study_hours, Length: 1000000, dtype: float64

In [57]:
df[df["weekly_self_study_hours"]>30]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
113,114,32.2,84.4,4.9,100.0,A
125,126,30.3,75.7,1.1,100.0,A
179,180,34.0,100.0,0.6,100.0,A
209,210,40.0,68.1,6.7,100.0,A
220,221,31.2,95.1,2.1,100.0,A
...,...,...,...,...,...,...
999344,999345,30.1,95.3,8.9,100.0,A
999459,999460,34.0,75.0,6.5,100.0,A
999505,999506,34.5,78.5,3.3,100.0,A
999724,999725,33.8,100.0,4.6,100.0,A
999952,999953,33.9,77.7,3.2,100.0,A

In [58]:
df.sort_values("weekly_self_study_hours")

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
481797,481798,0.0,84.0,9.5,56.8,C
970294,970295,0.0,79.2,9.0,41.1,D
970234,970235,0.0,94.3,6.0,37.3,F
481775,481776,0.0,73.4,5.6,53.9,D
481761,481762,0.0,83.6,9.8,45.3,D
...,...,...,...,...,...,...
937007,937008,40.0,67.6,6.3,100.0,A
156138,156139,40.0,81.3,6.2,100.0,A
895979,895980,40.0,86.7,6.7,100.0,A
539838,539839,40.0,63.1,2.9,100.0,A
721029,721030,40.0,74.0,5.3,100.0,A

In [59]:
df.rename(columns={"weekly_self_study_hours":"weekly_self_study_hours_"})

,student_id,weekly_self_study_hours_,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [60]:
df.drop("weekly_self_study_hours",axis=1)

,student_id,attendance_percentage,class_participation,total_score,grade
0,1,95.6,3.8,97.9,A
1,2,80.0,2.5,83.9,B
2,3,86.3,5.3,100.0,A
3,4,70.2,7.0,100.0,A
4,5,81.9,6.9,92.0,A
...,...,...,...,...,...
999995,999996,95.5,4.8,100.0,A
999996,999997,82.7,6.7,88.3,A
999997,999998,85.1,5.8,87.9,A
999998,999999,90.0,5.3,100.0,A
999999,1000000,84.6,4.1,100.0,A

In [63]:
!git init

Initialized empty Git repository in C:/Users/user/4ik25cs069/.git/

In [64]:
!git config user.name "indrajith H B"

In [65]:
!git config user.email "2025cs_indrajithhb_c@nie.ac.in

In [66]:
!git remote add origin https://github.com/2025csindrajithhbc/DAV-Lab.git

In [67]:
!git add 4ik25cs069.ipynb

fatal: pathspec '4ik25cs069.ipynb' did not match any files